  [
    {
      _id: "6652ded058df5a18b68cdf75",
      user_id: 1,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf76",
      user_id: 2,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf77",
      user_id: 3,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf78",
      user_id: 4,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf79",
      user_id: 5,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf7a",
      user_id: 6,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf7b",
      user_id: 7,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf7c",
      user_id: 8,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf7d",
      user_id: 9,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf7e",
      user_id: 10,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf7f",
      user_id: 11,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf80",
      user_id: 12,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf81",
      user_id: 13,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf82",
      user_id: 14,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf83",
      user_id: 15,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf84",
      user_id: 16,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf85",
      user_id: 17,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf86",
      user_id: 18,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf87",
      user_id: 19,
      top_id: 1,
      attended: true
    },
    {
      _id: "6652ded058df5a18b68cdf88",
      user_id: 20,
      top_id: 1,
      attended: true
    }
  ];
  
  